### PR TITLE
Add secure option for websockets

### PR DESCRIPTION
**Pull request by minemidnight**
Allows people to connect using wss rather than force ws

### CODE REVIEW

**Comment by macdja38** [comment]
What did spaces before parenthesis ever do to you?

**Comment by minemidnight** [comment]
I'm pretty sure either VSCode or ESLint just changed that on save.  :triumph:

**Comment by minemidnight** [comment]
https://github.com/briantanner/eris-lavalink/blob/master/.eslintrc.json#L104

This was just following the ESLint config

**Comment by macdja38** [comment]
Not up to me, but the rule you linked is actually about block spacing... like before a block... as in {}

https://eslint.org/docs/rules/space-before-blocks

the rules on this would be
https://eslint.org/docs/rules/space-before-function-paren
and something I can't find.

**Pull request merged**
